delete from users;
insert into users (username, "firstName", "lastName", "hasIPSec") values 
('agurkov', 'Александр', 'Гурков', true),
('elenakrut', 'Елена', 'Крутых', true),
('marinavlasova', 'Марина', 'Власова', true),
('masharub', 'Мария', 'Рубцова', true),
('kirillbur', 'Кирилл', 'Бурмистров', true),
('vladkol', 'Владислав', 'К', true),
('lapsha', 'Никита', 'Лапша', true),
('nikitabodr', 'Никита', 'Бодров', true),
('egorzar', 'Егор', 'Заруба', true),
('sergeysem', 'Сергей', 'Семикин', true),
('dimanscorb','Дмитрий','Скорбовский', true),
('antonsh','Антон','Шалыгин', true),
('tatyanayak','Татьяна','Яковлева', true),
('dashasom','Даша','Самсонова', true),
('irina_skylungs','Ирина','Варгас', true),
('veraslad','Вера','Сладкова', true),
('volm','Владимир','Матвиенко', true),
('zanna','Анна','Быкова', true),
('lenarul','Елена','Рулёва', true)
