delete from "VpnUser";
insert into "VpnUser" (username, "firstName", "lastName") values 
('agurkov', 'Александр', 'Гурков'),
('elenakrut', 'Елена', 'Крутых'),
('marinavlasova', 'Марина', 'Власова'),
('masharub', 'Мария', 'Рубцова'),
('kirillbur', 'Кирилл', 'Бурмистров'),
('vladkol', 'Владислав', 'К'),
('lapsha', 'Никита', ''),
('nikitabodr', 'Никита', 'Бодров'),
('egorzar', 'Егор', 'Заруба'),
('sergeysem', 'Сергей', 'Семикин'),
('dimanscorb','Дмитрий','Скорбовский'),
('antonsh','Антон','Шалыгин'),
('tatyanayak','Татьяна','Яковлева'),
('dashasom','Даша','Самсонова'),
('irina_skylungs','Ирина','Варгас'),
('veraslad','Вера','Сладкова'),
('volm','Владимир','Матвиенко'),
('zanna','Анна','Быкова'),
('lenarul','Елена','Рулёва')
