services:
    app:
        image: vpn-bot
        network_mode: host
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        volumes:
            - type: bind
              source: ${HOST_SOURCE:-/root}
              target: ${HOST_TARGET:-/app/hostfs}
            - ./scripts:/app/scripts
            - /usr/bin/wireguard.sh:/usr/bin/wireguard.sh
            - /usr/bin/ikev2.sh:/usr/bin/ikev2.sh
            - /etc/ipsec.d:/etc/ipsec.d
            - /lib/modules:/lib/modules:ro
            - /etc/wireguard:/etc/wireguard
            - /etc/sysctl.conf:/etc/sysctl.conf:ro
            - /etc/sysctl.d:/etc/sysctl.d:ro
            - /etc/ipsec.conf:/etc/ipsec.conf:ro
