services:
    tesseract-api:
        container_name: tesseract-api
        build:
            context: ./apps/api
            dockerfile: ./Dockerfile
        image: tesseract-api
        env_file: .env.api
        ports:
            - 3002:3002
        restart: always
        networks:
            - tesseract-network
    tesseract-bot:
        container_name: tesseract-bot
        build:
            context: ./apps/users
            dockerfile: ./Dockerfile
        image: tesseract-bot
        env_file: .env.bot
        ports:
            - 4000:4000
        restart: always
        networks:
            - tesseract-network
networks:
    tesseract-network:
        external: true
