services:
    app:
        image: users-bot
        container_name: users-bot
        build:
            context: .
            dockerfile: ./apps/users/Dockerfile
        env_file: .env
        network_mode: host
        restart: always
