services:
    vpndb:
        image: postgres:14.7-alpine
        container_name: vpndb
        network_mode: host
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - vpndata:/var/lib/postgresql/data
            - ./data.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 5s
            timeout: 45s
            retries: 5
