version: '3.9'

services:
  vpndb:
    image: postgres:14.7-alpine
    container_name: vpndb
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - vpndata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 45s
      retries: 5

  vpnbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vpnbot
    network_mode: host
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    environment:
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
    depends_on:
      vpndb: 
        condition: service_healthy

volumes:
  vpndata:
