version: '3.4'

services:
  vpnbot:
    image: vpnbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 45532:45532
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/index.js"]
  postgres:
    image: postgres:latest