version: '3.9'

services:
  vpnbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    env_file:
      - .env
    environment:
      NODE_ENV: production

  vpndb:
    image: postgres:14.7-bullseye
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - vpndata:/data/db
      - ./pg-init.sh:/docker-entrypoint-initdb.d/pg-init.sh:ro
      - ./postgresql.conf:/etc/postgresql/14/main/postgresql.conf

volumes:
  vpndata:
