services:
    app:
        image: vpn-bot
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        volumes:
            - ${IKE_CLIENTS_DIR}:${IKE_CONTAINER_DIR:-/app/ikev2-clients}
            - ${WG_CLIENTS_DIR}:${WG_CONTAINER_DIR:-/app/wg-clients}
            - ./scripts:/app/scripts
            - /usr/bin/wireguard.sh:/usr/bin/wireguard.sh
            - /usr/bin/ikev2.sh:/usr/bin/ikev2.sh
            - /etc/ipsec.d:/etc/ipsec.d
            - /lib/modules:/lib/modules:ro
            - /etc/wireguard:/etc/wireguard
            - /etc/sysctl.conf:/etc/sysctl.conf:ro
            - /etc/sysctl.d:/etc/sysctl.d:ro
            - /etc/ipsec.conf:/etc/ipsec.conf:ro
            - /opt/src:/opt/src:ro
            - /usr/local/sbin:/usr/local/sbin:ro
            - /usr/local/libexec:/usr/local/libexec:ro
            - /usr/bin/wg:/usr/bin/wg
            - /usr/bin/qrencode:/usr/bin/qrencode:ro
            - /usr/lib/x86_64-linux-gnu/libqrencode.so.4:/usr/lib/x86_64-linux-gnu/libqrencode.so.4:ro
            - /usr/lib/x86_64-linux-gnu/libqrencode.so.4.1.1:/usr/lib/x86_64-linux-gnu/libqrencode.so.4.1.1:ro
            - /usr/lib/x86_64-linux-gnu/libpng16.so.16:/usr/lib/x86_64-linux-gnu/libpng16.so.16:ro
            - /usr/lib/x86_64-linux-gnu/libpng16.so.16.39.0:/usr/lib/x86_64-linux-gnu/libpng16.so.16.39.0:ro
