services:
    app:
        image: vpn-bot
        network_mode: host
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        volumes:
            - type: bind
              source: /root
              target: /app/host-fs
            - ./scripts:/app/scripts
            - /usr/bin/ikev2.sh:/usr/bin/ikev2.sh
            - /usr/bin/wireguard.sh:/usr/bin/wireguard.sh
