services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        network_mode: host
        volumes:
            - grafana-storage:/var/lib/grafana # Сохраняем данные Grafana
            - /etc/ssl/certs/grafana:/etc/ssl/certs/grafana:ro # Твои SSL-серты
        environment:
            - GF_SERVER_PROTOCOL=https
            - GF_SERVER_CERT_FILE=/etc/ssl/certs/grafana/cert.pem
            - GF_SERVER_CERT_KEY=/etc/ssl/certs/grafana/key.pem
        restart: unless-stopped

volumes:
    grafana-storage:
