global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9099']

    - job_name: 'node'
      static_configs:
          - targets: ['localhost:9100'] # Node Exporter

    - job_name: 'wg'
      static_configs:
          - targets: ['localhost:9586'] # Wireguard
