import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
async function main() {
	await prisma.user.createMany({
		data: [
			{
				username: 'nu-visage',
				firstName: 'Александр',
				lastName: 'С',
				price: 80,
				telegramLink: 'https://t.me/nu_visage',
				telegramId: '147350518',
			},
			{
				username: 'anabik',
				firstName: 'Александр',
				lastName: 'Х',
				price: 80,
				telegramLink: 'https://t.me/Anabik322',
				telegramId: '483751237',
			},
			{
				username: 'alexey-e',
				firstName: 'Алексей',
				lastName: 'Ермаков',
				price: 80,
				telegramId: '598018892',
			},
			{
				username: 'alexey-skovorodkin',
				firstName: 'Алексей',
				lastName: 'Сковородкин',
				price: 80,
				telegramId: '50910961',
			},
			{
				username: 'alexslezich',
				firstName: 'Алексей',
				lastName: 'Слёзкин',
				price: 80,
				telegramLink: 'https://t.me/alexslezich',
				telegramId: '640716011',
			},
			{
				username: 'zh',
				firstName: 'Алексей',
				lastName: 'Э',
				telegramId: '794803248',
				price: 80,
			},
			{
				username: 'we4lu',
				firstName: 'Алена',
				lastName: 'З',
				telegramLink: 'https://t.me/we4lu',
				telegramId: '230403707',
				price: 80,
			},
			{
				username: 'anastasia-l',
				telegramLink: 'https://t.me/lapshinanastia',
				firstName: 'Анастасия',
				lastName: 'Лапшина',
				telegramId: '297562229',
				price: 80,
			},
			{
				username: 'angelina-vyugina',
				firstName: 'Ангелина',
				lastName: 'Вьюгина',
				telegramLink: 'https://t.me/vyuginaA',
				telegramId: '266937317',
				price: 80,
			},
			{
				username: 'Andryushka',
				firstName: 'Андрей',
				lastName: 'К',
				telegramId: '735935391',
				price: 80,
			},
			{
				username: 'andrey-karpov',
				firstName: 'Андрей',
				lastName: 'Карпов',
				telegramId: '336979028',
				telegramLink: 'https://t.me/dreuot',
				price: 80,
			},
			{
				username: 'greml1n300',
				telegramLink: 'https://t.me/greml1n300',
				firstName: 'Андрей',
				lastName: 'М',
				telegramId: '267044281',
				price: 80,
			},
			{
				username: 'angelinabur',
				telegramLink: 'https://t.me/https_505',
				firstName: 'Анжелика',
				lastName: 'Бурмистрова',
				telegramId: '1346261949',
				free: true,
				price: 80,
			},
			{
				username: 'zanna',
				telegramLink: 'https://t.me/z_ann_a',
				firstName: 'Анна',
				lastName: 'Земскова',
				telegramId: '328123449',
				price: 80,
			},
			{
				username: 'anlookk',
				telegramLink: 'https://t.me/Anlookk',
				firstName: 'Анна',
				lastName: 'Федосова',
				telegramId: '1463598154',
				price: 80,
			},
			{
				username: 'anton-gusev',
				firstName: 'Антон',
				lastName: 'Гусев',
				telegramId: '460929905',
				price: 80,
			},
			{
				username: 'avreolus',
				firstName: 'Антон',
				lastName: 'Д',
				telegramId: '610622243',
			},
			{
				username: 'antonsh',
				firstName: 'Антон',
				lastName: 'Ш',
				telegramId: '261146269',
				price: 80,
			},
			{
				username: 'arina-loguzova',
				firstName: 'Арина',
				lastName: 'Логузова',
				telegramLink: 'https://t.me/arkatangens',
				telegramId: '435870136',
				price: 80,
			},
			{
				username: 'artak',
				firstName: 'Артак',
				lastName: 'С',
				telegramId: '5454652248',
				price: 80,
			},
			{
				username: 'valentin-o',
				firstName: 'Валентин',
				lastName: 'Орлов',
				telegramId: '873697298',
				telegramLink: 'https://t.me/VelOrlov',
				price: 80,
			},
			{
				username: 'ivan-k',
				firstName: 'Иван',
				lastName: 'Кондратьев',
				telegramId: '726960246',
				telegramLink: 'https://t.me/xpoweroflawx',
				price: 80,
			},
			{
				username: 'veraslad',
				firstName: 'Вера',
				lastName: 'Сладкова',
				telegramId: '759485108',
				telegramLink: 'https://t.me/vera_mega_flame',
				price: 80,
			},
			{
				username: 'verokuznetsova',
				firstName: 'Вероника',
				lastName: 'Кузнецова',
				telegramId: '364128303',
				telegramLink: 'https://t.me/verokuznetsova',
				price: 100,
			},
			{
				username: 'beaverV',
				firstName: 'Виктор',
				lastName: 'Бобров',
				telegramId: '702046340',
				telegramLink: 'https://t.me/beaverV',
				price: 80,
			},
			{
				username: 'viktor-medvedev',
				firstName: 'Виктор',
				lastName: 'Медведев',
				telegramId: '529032476',
				telegramLink: 'https://t.me/Berserk131313',
				price: 80,
			},
			{
				username: 'titanda_eru',
				firstName: 'Виктория',
				lastName: 'И',
				telegramId: '743421149',
				telegramLink: 'https://t.me/titanda_eru',
				price: 80,
			},
			{
				username: 'viktoria-sch',
				firstName: 'Виктория',
				lastName: 'Щербакова',
				telegramId: '1058661143',
				price: 80,
			},
			{
				username: 'viktor-k',
				firstName: 'Виктор',
				lastName: 'Крашенинников',
				telegramId: '472357989',
				telegramLink: 'https://t.me/vityao113',
				price: 80,
			},
			{
				username: 'vladkol',
				firstName: 'Влад',
				lastName: 'К',
				telegramId: '722744360',
				telegramLink: 'https://t.me/LoryInsanerzxc',
				price: 80,
				free: true,
			},
			{
				username: 'volmn',
				firstName: 'Владимир',
				lastName: 'М',
				telegramId: '419067896',
				telegramLink: 'https://t.me/Volm1',
				price: 80,
			},
			{
				username: 'darinow',
				firstName: 'Дарья',
				lastName: 'Верижникова',
				telegramId: '907279512',
				telegramLink: 'https://t.me/darinow',
				price: 80,
			},
			{
				username: 'darya-nesterova',
				firstName: 'Дарья',
				lastName: 'Нестеров',
				telegramId: '68565162',
				telegramLink: 'https://t.me/ne_dash_v',
				price: 80,
			},
			{
				username: 'dashasom',
				firstName: 'Дарья',
				lastName: 'Самсонова',
				telegramId: '215363244',
				telegramLink: 'https://t.me/ja_boodoo_voodoo',
				price: 80,
			},
			{
				username: 'A.Alexandr.A',
				firstName: 'Александр',
				lastName: 'Самсонов',
				telegramId: '151877224',
				telegramLink: 'https://t.me/A_ALEXANDR_A',
				price: 80,
			},
			{
				username: 'dima-rudnov',
				firstName: 'Дмитрий',
				lastName: 'Руднов',
				telegramId: '886350651',
				telegramLink: 'https://t.me/rudnov_x',
				price: 80,
			},
			{
				username: 'dima-antipov',
				firstName: 'Дмитрий',
				lastName: 'Антипов',
				telegramId: '353915022',
				telegramLink: 'https://t.me/DmitryPsych',
				price: 80,
			},
			{
				username: 'egor-zaruba',
				firstName: 'Егор',
				lastName: 'Заруба',
				telegramId: '463407423',
				telegramLink: 'https://t.me/BelyOgonek',
				price: 80,
			},
			{
				username: 'ekaterina-kuz',
				firstName: 'Екатерина',
				lastName: 'Кузнецова',
				telegramId: '2056775149',
				price: 80,
			},
			{
				username: 'ekaterina-pevcheva',
				firstName: 'Екатерина',
				lastName: 'Певчева',
				telegramId: '5106584304',
				price: 80,
			},
			{
				username: 'justleni',
				firstName: 'Елена',
				lastName: 'Валкова',
				telegramId: '522975666',
				telegramLink: 'https://t.me/justleni',
				price: 80,
			},
			{
				username: 'lena-krutykh',
				firstName: 'Елена',
				lastName: 'Крутых',
				telegramId: '716760647',
				telegramLink: 'https://t.me/dr_krutykhelena',
				price: 80,
			},
			{
				username: 'lenarul',
				firstName: 'Елена',
				lastName: 'Рулёва',
				telegramId: '787481425',
				telegramLink: 'https://t.me/RulevaElena62',
				price: 80,
			},
			{
				username: 'zlata-selifanova',
				firstName: 'Злата',
				lastName: 'Селифанова',
				telegramId: '441331434',
				telegramLink: 'https://t.me/zlaattiikk',
				price: 80,
				free: true,
			},
			{
				username: 'igor-che',
				firstName: 'Игорь',
				lastName: 'Черваков',
				telegramId: '144670568',
				telegramLink: 'https://t.me/CHIgor1',
				price: 80,
			},
			{
				username: 'ilya-danilov',
				firstName: 'Илья',
				lastName: 'Данилов',
				telegramId: '492129267',
				telegramLink: 'https://t.me/jewelhux',
				price: 80,
			},
			{
				username: 'ilya-polin',
				firstName: 'Илья',
				lastName: 'Полин',
				telegramId: '5443196979',
				telegramLink: 'https://t.me/emdance_creator',
				price: 80,
				free: true,
			},
			{
				username: 'irina_skylungs',
				firstName: 'Ирина',
				lastName: 'Дворецкова',
				telegramId: '1079388815',
				telegramLink: 'https://t.me/without_emotions',
				price: 80,
			},
			{
				username: 'iren_poll',
				firstName: 'Ирина',
				lastName: 'П',
				telegramId: '989256380',
				telegramLink: 'https://t.me/IrenPoll',
				price: 80,
			},
			{
				username: 'kate-weirdgeddon',
				firstName: 'Екатерина',
				lastName: 'Кондракова',
				telegramId: '414295617',
				telegramLink: 'https://t.me/weirdgeddon',
				price: 80,
			},
			{
				username: 'bober',
				firstName: 'Кирилл',
				lastName: 'Б',
				telegramId: '1973939191',
				telegramLink: 'https://t.me/Abalduy73y',
				price: 80,
			},
			{
				username: 'kirill-bur',
				firstName: 'Кирилл',
				lastName: 'Бурмистров',
				telegramId: '376593682',
				telegramLink: 'https://t.me/grawler',
				price: 80,
			},
			{
				username: 'larisa-brag',
				firstName: 'Лариса',
				lastName: 'Брагина',
				telegramId: '847983145',
				telegramLink: 'https://t.me/larisabrag',
				price: 80,
			},
			{
				username: 'lerakus',
				firstName: 'Валерия',
				lastName: 'Кусова',
				telegramId: '209455126',
				telegramLink: 'https://t.me/ayedeyl',
				price: 80,
			},
			{
				username: 'beautystar',
				firstName: 'Максим',
				lastName: 'Б',
				telegramId: '341536418',
				price: 80,
			},
			{
				username: 'maxim-che',
				firstName: 'Максим',
				lastName: 'Ч',
				telegramId: '743898483',
				telegramLink: 'https://t.me/z43245',
				price: 80,
			},
			{
				username: 'marina-vlasova',
				firstName: 'Марина',
				lastName: 'Власова',
				telegramId: '348181560',
				telegramLink: 'https://t.me/otterfromthecupboard',
				price: 80,
			},
			{
				username: 'maria-lukhina',
				firstName: 'Мария',
				lastName: 'Люхина',
				telegramId: '403245382',
				telegramLink: 'https://t.me/bybykkaa',
				price: 80,
			},
			{
				username: 'maria-rub',
				firstName: 'Мария',
				lastName: 'Рубцова',
				telegramId: '369829061',
				telegramLink: 'https://t.me/drmrxx',
				price: 80,
			},
			{
				username: 'maria-titova',
				firstName: 'Мария',
				lastName: 'Титова',
				telegramId: '1236333408',
				price: 80,
			},
			{
				username: 'maria-tolkova',
				firstName: 'Мария',
				lastName: 'Толкова',
				telegramId: '906989598',
				telegramLink: 'https://t.me/mtolkova',
				price: 80,
			},
			{
				username: 'mikhail-ya',
				firstName: 'Михаил',
				lastName: 'Яблочкин',
				telegramId: '255442793',
				telegramLink: 'https://t.me/kaban62',
				price: 80,
			},
			{
				username: 'nad-petr',
				firstName: 'Надежда',
				lastName: 'Петровцева',
				telegramId: '1718673837',
				price: 80,
			},
			{
				username: 'natalia-lapshina',
				firstName: 'Наталья',
				lastName: 'Лапшина',
				telegramId: '236477852',
				telegramLink: 'https://t.me/lapshina_nataliia',
				price: 80,
			},
			{
				username: 'nestor',
				firstName: 'Нестор',
				lastName: 'Д',
				telegramId: '276251065',
				telegramLink: 'https://t.me/nestor_nestor',
				price: 80,
			},
			{
				username: 'nikita-bodrov',
				firstName: 'Никита',
				lastName: 'Бодров',
				telegramId: '328677678',
				telegramLink: 'https://t.me/nikitkabodrij',
				price: 80,
			},
			{
				username: 'kitsune',
				firstName: 'Николай',
				lastName: 'Г',
				telegramId: '114047410',
				telegramLink: 'https://t.me/kitsunekitsunekitsunekitsune',
				price: 80,
			},
			{
				username: 'pavel-obidin',
				firstName: 'Павел',
				lastName: 'Обидин',
				telegramId: '571266705',
				telegramLink: 'https://t.me/Leg0Last',
				price: 80,
			},
			{
				username: 'GRAO',
				firstName: 'Ровшан Ахмед Оглы',
				lastName: 'Г',
				telegramId: '1783348064',
				price: 80,
			},
			{
				username: 'agurkov',
				firstName: 'Александр',
				lastName: 'Гурков',
				telegramId: '435442614',
				telegramLink: 'https://t.me/salam_js',
				price: 80,
			},
			{
				username: 'sashacrespo',
				firstName: 'Александр',
				lastName: 'Линсов',
				telegramId: '792987535',
				telegramLink: 'https://t.me/sashacrespo',
				price: 80,
			},
			{
				username: 'sashacrespo',
				firstName: 'Александр',
				lastName: 'Линсов',
				telegramId: '792987535',
				telegramLink: 'https://t.me/sashacrespo',
				price: 80,
			},
			{
				username: 'serejkaaa62',
				firstName: 'Сергей',
				lastName: 'С',
				telegramId: '518675443',
				telegramLink: 'https://t.me/serejkaaa62',
				price: 80,
			},
			{
				username: 'sergey-volga',
				firstName: 'Сергей',
				lastName: 'Волга',
				telegramId: '247964606',
				telegramLink: 'https://t.me/tgws1337',
				price: 80,
			},
			{
				username: 'sergey-semikin',
				firstName: 'Сергей',
				lastName: 'Семикин',
				telegramId: '328674253',
				telegramLink: 'https://t.me/Cepeja',
				price: 80,
			},
			{
				username: 'sergey-che',
				firstName: 'Сергей',
				lastName: 'Черваков',
				telegramId: '185800302',
				telegramLink: 'https://t.me/callthecops',
				price: 80,
			},
			{
				username: 'smolikova',
				firstName: 'Александр',
				lastName: 'Смоликова',
				telegramId: '878616698',
				price: 80,
			},
			{
				username: 'tatyana-ya',
				firstName: 'Татьяна',
				lastName: 'Яковлева',
				telegramId: '841629201',
				telegramLink: 'https://t.me/yttdm_n',
				price: 80,
			},
			{
				username: 'edgar',
				firstName: 'Эдгар',
				lastName: 'Карапетян',
				telegramId: '820358842',
				telegramLink: 'https://t.me/EdgarKarapetyan19',
				price: 80,
			},
			{
				username: 'julia-borovskikh',
				firstName: 'Юлия',
				lastName: 'Боровских',
				telegramId: '74828144',
				telegramLink: 'https://t.me/Julls_core',
				price: 80,
			},
			{
				username: 'n-darina',
				firstName: 'Дарина',
				lastName: 'Н',
				telegramId: '197996353',
				telegramLink: 'https://t.me/N_Darina',
				price: 80,
			},
			{
				username: 'garrettrds',
				firstName: 'Андрей',
				lastName: 'Е',
				telegramId: '197996353',
				telegramLink: 'https://t.me/garrettrds',
				price: 80,
			},
			{
				username: 'melsky',
				firstName: 'Никита',
				lastName: 'Мельниченко',
				telegramId: '539630108',
				telegramLink: 'https://t.me/MelskyN',
				price: 80,
			},
		],
	});
}

main()
	.then(async () => {
		await prisma.$disconnect();
	})
	.catch(async e => {
		console.error(e);
		await prisma.$disconnect();
		process.exit(1);
	});
