services:
    vpn-db:
        image: postgres:17.2-bookworm
        container_name: vpn-db
        ports:
            - '54333:5432'
        restart: unless-stopped
        env_file:
            - .env
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: JFJ4GSvryTwBW1
            POSTGRES_DB: vpn
        volumes:
            - vpn-data:/var/lib/postgresql/data
            - ./data.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 5s
            timeout: 45s
            retries: 5
    backups-bot:
        image: backups-bot
        container_name: backups-bot
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        network_mode: host
        restart: unless-stopped
        volumes:
            - backups:/home/vpnadmin/backups

volumes:
    vpn-data:
    backups:
