services:
    vpn-db:
        image: postgres:17.2-bookworm
        container_name: vpn-db
        ports:
            - '54333:5432'
        restart: unless-stopped
        env_file:
            - .env
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: JFJ4GSvryTwBW1
            POSTGRES_DB: vpn
        volumes:
            - vpn-bot_vpn-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U admin -d vpn']
            interval: 10s
            timeout: 30s
            retries: 5
    backups-bot:
        image: backups-bot
        container_name: backups-bot
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        network_mode: host
        restart: unless-stopped
        volumes:
            - backups:/home/vpnadmin/backups

volumes:
    vpn-bot_vpn-data:
        external: true
    backups:
