FROM node:lts-bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \ 
    qrencode wireguard apt-utils \
    wget dnsutils openssl ca-certificates iproute2 unzip zip curl \
    net-tools iptables libnss3-tools 