services:
    app:
        image: tesseract-api
        container_name: tesseract-api
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: .env
        network_mode: host
        restart: always
