services:
  api:
    container_name: tesseract-api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tesseract-api
    env_file: .env
    network_mode: host
    restart: always
    volumes:
      - /etc/ssl/certs/tg:/etc/ssl/certs/tg:ro
