name: Build and Deploy keys-bot on 3X-UI server

run-name: "Build and Deploy keys-bot on 3X-UI server"

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Target environment"
                required: true
                default: t
                type: choice
                options:
                    - neth-eternal-xray

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.VPN_SERVER_HOST }}
                  username: ${{ secrets.VPN_SERVER_USERNAME }}
                  key: ${{ secrets.VPN_SERVER_SSH_KEY }}
                  script: |
                      cd ${{ secrets.VPN_SERVER_APP_DIRECTORY }}/apps/keys
                      git pull
                      docker-compose -f ./docker-compose.3xui.yml build --no-cache app
                      docker-compose up -d app
