name: Update exporters

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment'
                required: true
                default: t
                type: choice
                options:
                    - us2
                    - neth
                    - brazil
                    - msk
                    - greece
                    - norway

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.1
              with:
                  ssh-private-key: ${{ secrets.VPN_SERVER_SSH_KEY }}

            - name: Add VPN server to known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.VPN_SERVER_HOST }} >> ~/.ssh/known_hosts

            - name: Upload docker-compose.yml via SSH
              run: |
                  cat ./monitoring/docker-compose.yml | ssh ${{ secrets.VPN_SERVER_USERNAME }}@${{ secrets.VPN_SERVER_HOST }} "cat > ${{ secrets.VPN_SERVER_MON_DIRECTORY }}/docker-compose.yml"

            - name: Upload web.yml via SSH
              run: |
                  cat ./monitoring/web.yml | ssh ${{ secrets.VPN_SERVER_USERNAME }}@${{ secrets.VPN_SERVER_HOST }} "cat > ${{ secrets.VPN_SERVER_MON_DIRECTORY }}/prometheus/config/web.yml"

            - name: Restart exporters on server
              run: |
                  ssh ${{ secrets.VPN_SERVER_USERNAME }}@${{ secrets.VPN_SERVER_HOST }} '
                    cd ${{ secrets.VPN_SERVER_MON_DIRECTORY }}
                    docker compose up -d
                  '
